components:
  schemas:
    ProductCreateRequest:
      type: object
      properties:
        productName:
          type: string
          description: "The name of the product"
        productDescription:
          type: string
          description: "The description of the product"

    ProductCreateResponse:
      type: object
      x-implements: ["at.ymeri.open_api_samples.dto.ResponseInterface<at.ymeri.open_api_samples.dto.Product,at.ymeri.open_api_samples.dto.ResponseCommon>"]
      properties:
        responseCommon:
          $ref: "response-common.yaml#/components/schemas/ResponseCommon"
        response:
          $ref: "#/components/schemas/Product"

    ProductGetResponse:
      type: object
      x-implements: ["at.ymeri.open_api_samples.dto.ResponseInterface<at.ymeri.open_api_samples.dto.Product,at.ymeri.open_api_samples.dto.ResponseCommon>"]
      properties:
        responseCommon:
          $ref: "response-common.yaml#/components/schemas/ResponseCommon"
        response:
          $ref: "#/components/schemas/Product"

    Product:
      type: object
      allOf:
        - $ref: "parent-model.yaml#/components/schemas/ApiModel"
        - type: object
          properties:
            productName:
              type: string
              description: "The name of the file"
            productDescription:
              type: array
              items:
                type: string

