components:
  schemas:
    ProductCreateRequest:
      type: object
      properties:
        productName:
          type: string
          description: "The name of the product"
        productDescription:
          type: string
          description: "The description of the product"

    ProductCreateResponse:
      type: object
      x-implements: ["at.ymeri.open_api_samples.dto.ResponseInterface<at.ymeri.open_api_samples.dto.Product>"]
      properties:
        responseCommon:
          type: object
          properties:
            message:
              type: string
              example: "1 product created successfully"
        response:
          $ref: "#/components/schemas/Product"

    ProductGetResponse:
      type: object
      x-implements: ["at.ymeri.open_api_samples.dto.ResponseInterface<at.ymeri.open_api_samples.dto.Product>"]
      properties:
        responseCommon:
          type: object
          properties:
            message:
              type: string
              example: "1 product created successfully"
        response:
          $ref: "#/components/schemas/Product"

    Product:
      type: object
      allOf:
        - $ref: "parent-model.yaml#/components/schemas/ApiModel"
        - type: object
          properties:
            productName:
              type: string
              description: "The name of the file"
            productDescription:
              type: array
              items:
                type: string

